Algoritmo "consumo"

Var
       distanPerco : inteiro
       combuGasto, consuMedio : real

Inicio

       escreva("Distancia percorrida:")
       leia(distanPerco)
       escreva("Combustivel gasto:")
       leia(combuGasto)
       
       consuMedio <- distanPerco / combuGasto
       
       escreva("Consumo Medio: ", consuMedio:5:3)
       
      
      

          
          
          
         
         
         




Fimalgoritmo