Algoritmo "pagamento"

Var

   nome : caractere
   valorPorHora,pag   : real
   horaTraba : inteiro

Inicio

      escreva("Nome:")
      leia(nome)
      escreva("Valor da hora trabalhada: ")
      leia(valorPorHora)
      escreva("Horas trabalhadas: ")
      leia(horaTraba)
      
      pag <- valorPorHora * horaTraba
      
      escreva("O pagamento para ", nome, " deve ser ", pag:4:2)
      
      

          
          
          
         
         
         




Fimalgoritmo